### ISSUE TITLE
Does AskSonic proxy the streams or just point to the stream from the underlying Subsonic server?

### ISSUE THREAD

**Issue by simensen** [srichter/asksonic#12]
This may seem obvious, but I'm curious if AskSonic proxies the content to Alexa or if it just points to the appropriate stream from the Subsonic server. Knowing whether it's going to proxy the stream versus referencing it may help me better determine how I want to host AskSonic resource-wise.

**Comment by srichter** [comment]
It just points Alexa to the Subsonic "Stream URL" for the track
