### ISSUE TITLE
[Request] Multiroom-Audio 

### ISSUE THREAD

**Issue by ffidan61** [srichter/asksonic#13]
Hi thanks for this repo.

Would it also be possible to activate multiroom audio? 

Regards

**Comment by srichter** [comment]
From a quick glance it [doesn't](https://alexa.uservoice.com/forums/906892-alexa-skills-developer-voice-and-vote/suggestions/33800590-bring-multi-room-support-to-audioplayer-api-stream) seem like it's possible to do with the AudioPlayer API yet. Feel free to reopen this once it is possible and I'll mark it as a feature request
